# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""DeepSeek Janus: AR stage → diffusion stage bridges.

Two bridges are provided:

  ``ar2generation``
    AR text stage → JanusPipeline (diffusion).
    Stage 0 outputs natural-language text (prompt refinement / caption).
    Stage 1 runs the full AR image token loop + VQ decode.

  ``ar_tokens_to_vq``
    AR image-token stage → JanusVQDecodePipeline (diffusion).
    Stage 0 outputs image token IDs (576 tokens, generated by
    :class:`JanusForImageGeneration` via vLLM's optimised AR engine).
    Stage 1 runs VQ decode to produce the final image.

Pattern aligns with :mod:`vllm_omni.model_executor.stage_input_processors.hunyuan_image3`.
"""

from __future__ import annotations

from typing import Any

import torch
from vllm.inputs import TextPrompt
from vllm.logger import init_logger

from vllm_omni.inputs.data import OmniTokensPrompt

logger = init_logger(__name__)


def ar2generation(
    stage_list: list[Any],
    engine_input_source: list[int],
    prompt: OmniTokensPrompt | TextPrompt | list | None = None,
    requires_multimodal_data: bool = False,
) -> list[dict[str, Any]]:
    """Build diffusion-stage request dicts from text AR outputs.

    Used by the two-stage topology where stage 0 (text AR) generates a
    refined prompt and stage 1 (JanusPipeline diffusion) does the full
    image generation (AR image tokens + VQ decode).
    """
    del requires_multimodal_data
    if not engine_input_source:
        raise ValueError("engine_input_source cannot be empty")

    source_stage_id = engine_input_source[0]
    if source_stage_id >= len(stage_list):
        raise IndexError(f"Invalid source stage_id: {source_stage_id}")

    if stage_list[source_stage_id].engine_outputs is None:
        raise RuntimeError(f"Stage {source_stage_id} has no outputs yet")

    ar_outputs = stage_list[source_stage_id].engine_outputs
    out: list[dict[str, Any]] = []

    if not isinstance(prompt, list):
        prompt = [prompt] if prompt is not None else [{}]

    for i, ar_row in enumerate(ar_outputs):
        ao = ar_row.outputs[0]
        ar_text = getattr(ao, "text", "") or ""

        original = prompt[i] if i < len(prompt) else {}
        if isinstance(original, dict):
            pass
        elif hasattr(original, "_asdict"):
            original = original._asdict()
        elif hasattr(original, "__dict__"):
            original = vars(original)
        else:
            original = {}

        base_prompt = original.get("prompt", "") or ""

        if ar_text.strip():
            merged = f"{base_prompt}\n{ar_text}".strip() if base_prompt else ar_text.strip()
        else:
            merged = base_prompt

        height = original.get("height", 384)
        width = original.get("width", 384)

        diffusion_input: dict[str, Any] = {
            "prompt": merged,
            "height": height,
            "width": width,
            "extra": {
                "ar_generated_text": ar_text,
                "base_prompt": base_prompt,
            },
        }

        mm_data = original.get("multi_modal_data")
        if mm_data:
            diffusion_input["multi_modal_data"] = mm_data

        for key in ("seed", "num_inference_steps", "guidance_scale"):
            if key in original:
                diffusion_input[key] = original[key]

        logger.debug(
            "[ar2generation] merged prompt len=%d (base=%d ar=%d)",
            len(merged),
            len(base_prompt),
            len(ar_text),
        )
        out.append(diffusion_input)

    return out


def ar_tokens_to_vq(
    stage_list: list[Any],
    engine_input_source: list[int],
    prompt: OmniTokensPrompt | TextPrompt | list | None = None,
    requires_multimodal_data: bool = False,
) -> list[dict[str, Any]]:
    """Build VQ-decode request dicts from AR image-token outputs.

    Used by the two-stage topology where stage 0 (AR image token generation
    via :class:`JanusForImageGeneration` with full vLLM optimisations)
    outputs image token grids and stage 1 (JanusVQDecodePipeline) decodes
    them to RGB images.

    The AR stage outputs image token IDs via sampled_token_ids (576 tokens
    per request).  This bridge packages them for the VQ decoder.
    """
    del requires_multimodal_data
    if not engine_input_source:
        raise ValueError("engine_input_source cannot be empty")

    source_stage_id = engine_input_source[0]
    if source_stage_id >= len(stage_list):
        raise IndexError(f"Invalid source stage_id: {source_stage_id}")

    if stage_list[source_stage_id].engine_outputs is None:
        raise RuntimeError(f"Stage {source_stage_id} has no outputs yet")

    ar_outputs = stage_list[source_stage_id].engine_outputs
    out: list[dict[str, Any]] = []

    if not isinstance(prompt, list):
        prompt = [prompt] if prompt is not None else [{}]

    for i, ar_row in enumerate(ar_outputs):
        # Image tokens: either from structured output or sampled token IDs
        image_tokens = None

        # Try extracting from the output's structured fields
        if hasattr(ar_row, "image_tokens"):
            image_tokens = ar_row.image_tokens
        elif hasattr(ar_row, "image_token_ids"):
            image_tokens = ar_row.image_token_ids
        elif len(ar_row.outputs) > 0:
            # Extract from sampled token IDs (576 tokens per image)
            sampled_ids = getattr(ar_row.outputs[0], "token_ids", None) or []
            if sampled_ids and len(sampled_ids) >= 576:
                image_tokens = torch.tensor(sampled_ids[:576], dtype=torch.long)
            else:
                # Fallback: get all tokens from the output text
                all_ids = getattr(ar_row, "sampled_token_ids", None)
                if all_ids is not None and len(all_ids) >= 576:
                    image_tokens = all_ids[-576:]

        if image_tokens is None:
            logger.error("[ar_tokens_to_vq] Could not extract image tokens from AR output %d", i)
            continue

        original = prompt[i] if i < len(prompt) else {}
        if isinstance(original, dict):
            pass
        elif hasattr(original, "_asdict"):
            original = original._asdict()
        elif hasattr(original, "__dict__"):
            original = vars(original)
        else:
            original = {}

        height = original.get("height", 384)
        width = original.get("width", 384)
        img_size = original.get("img_size", max(height, width))

        diffusion_input: dict[str, Any] = {
            "prompt": original.get("prompt", ""),
            "height": height,
            "width": width,
            "extra": {
                "image_tokens": image_tokens,
                "img_size": img_size,
            },
        }

        for key in ("seed", "num_inference_steps", "guidance_scale"):
            if key in original:
                diffusion_input[key] = original[key]

        logger.debug(
            "[ar_tokens_to_vq] request %d: image_tokens shape=%s",
            i,
            getattr(image_tokens, "shape", "?") if hasattr(image_tokens, "shape") else len(image_tokens),
        )
        out.append(diffusion_input)

    return out
